const player = new APlayer({
    element: document.getElementById('player'),
    mini: false,
    autoplay: false,
    lrcType: false,
    mutex: true,
    theme: '#ad7a86',
    order: 'list',
    audio: [ {
        name: '虞兮叹',
        artist: '闻人听書',
        url: 'http://music.ruoyi.vip/yuxitan',
        cover: './music/cover/yuxitan.jpg',
        theme: '#ebd0c2'
    }, {
        name: '西楼别序',
        artist: '尹昔眠',
        url: 'http://music.ruoyi.vip/xiloubiexu',
        cover: './music/cover/xiloubiexu.jpg',
        theme: '#ebd0c2'
    }, {
        name: '1022-比尔的歌',
        artist: 'Bomb比尔',
        url: 'http://music.ruoyi.vip/bierdege',
        cover: './music/cover/bierdege.jpg',
        theme: '#46718b'
    }, {
        name: '失恋不怪她阵线联盟',
        artist: '拾贰',
        url: 'http://music.ruoyi.vip/slbgtzxlm',
        cover: './music/cover/slbgtzxlm.jpg',
        theme: '#ebd0c2'
    }, {
        name: '大风吹',
        artist: '王赫野',
        url: 'http://music.ruoyi.vip/dafengchui',
        cover: './music/cover/dafengchui.jpg',
        theme: '#46718b'
    }, {
        name: '察觉',
        artist: '逸霄',
        url: 'http://music.ruoyi.vip/chajue',
        cover: './music/cover/chajue.jpg',
        theme: '#46718b'
    }, {
        name: 'Ke Cap Gap Ba Gia',
        artist: '电音',
        url: 'http://music.ruoyi.vip/kecapcapbagia',
        cover: './music/cover/kecapcapbagia.jpg',
        theme: '#ebd0c2'
    }, {
        name: 'If You Feel My Love',
        artist: 'Blaxy Girls',
        url: 'http://music.ruoyi.vip/ifyoufeelmylove',
        cover: './music/cover/ifyoufeelmylove.jpg',
        theme: '#ebd0c2'
    }, {
        name: '大雨还在下',
        artist: '1个球',
        url: 'http://music.ruoyi.vip/dayuhaizaixia',
        cover: './music/cover/dayuhaizaixia.jpg',
        theme: '#ebd0c2'
    }, {
        name: '沦陷',
        artist: '王靖雯不胖',
        url: 'http://music.ruoyi.vip/lunxian',
        cover: './music/cover/lunxian.jpg',
        theme: '#ebd0c2'
    }, {
        name: '偏向',
        artist: '陈子晴',
        url: 'http://music.ruoyi.vip/pianxiang',
        cover: './music/cover/pianxiang.jpg',
        theme: '#ebd0c2'
    }, {
        name: '爱人错过',
        artist: '无孟子',
        url: 'http://music.ruoyi.vip/airencuoguo',
        cover: './music/cover/airencuoguo.jpg',
        theme: '#ebd0c2'
    }, {
        name: 'TA',
        artist: '不是花火呀',
        url: 'http://music.ruoyi.vip/ta',
        cover: './music/cover/ta.jpg',
        theme: '#ebd0c2'
    }, {
        name: 'Drown',
        artist: 'Martin Garrix / Clinton Kane',
        url: 'http://music.ruoyi.vip/drown',
        cover: './music/cover/drown.jpg',
        theme: '#ebd0c2'
    }, {
        name: '清空',
        artist: '王忻辰/苏星婕',
        url: 'http://music.ruoyi.vip/qingkong',
        cover: './music/cover/suxingjie.jpg',
        theme: '#ebd0c2'
    }, {
        name: '错位时空',
        artist: '艾辰',
        url: 'http://music.ruoyi.vip/cuoweishikong',
        cover: './music/cover/cwsk.jpg',
        theme: '#46718b'
    }, {
        name: '白月光与朱砂痣',
        artist: '大籽',
        url: 'http://music.ruoyi.vip/bygyzsz',
        cover: './music/cover/dazi.jpg',
        theme: '#ebd0c2'
    }, {
        name: '燕无歇',
        artist: '蒋雪儿',
        url: 'http://music.ruoyi.vip/yanwuxie',
        cover: './music/cover/jiangxueer.jpg',
        theme: '#ebd0c2'
    }, {
        name: '千千万万',
        artist: '深海鱼子酱',
        url: 'http://music.ruoyi.vip/qianqianwanwan',
        cover: './music/cover/shyzj.jpg',
        theme: '#ebd0c2'
    }, {
        name: '错季',
        artist: '秋原依',
        url: 'http://music.ruoyi.vip/cuoji',
        cover: './music/cover/qiuyuanyi.jpg',
        theme: '#ebd0c2'
    }, {
        name: '四季予你',
        artist: '程响',
        url: 'http://music.ruoyi.vip/sijiyuni',
        cover: './music/cover/chengxiang.jpg',
        theme: '#ebd0c2'
    }, {
        name: 'Dear John',
        artist: '比莉',
        url: 'http://music.ruoyi.vip/dearjohn',
        cover: './music/cover/bili.jpg',
        theme: '#ebd0c2'
    }, {
        name: '踏山河',
        artist: '是七叔呢',
        url: 'http://music.ruoyi.vip/tashanhe',
        cover: './music/cover/shiqishune.jpg',
        theme: '#46718b'
    }, {
        name: '醒不来的梦',
        artist: '回小仙',
        url: 'http://music.ruoyi.vip/xingbulaidemeng',
        cover: './music/cover/huixiaoxian.jpg',
        theme: '#ebd0c2'
    }, {
        name: '探清水河',
        artist: '师葭希',
        url: 'http://music.ruoyi.vip/tanshuiqinghe',
        cover: './music/cover/shixiaxi.jpg',
        theme: '#ebd0c2'
    }, {
        name: '迷失幻境',
        artist: 'IN-K / 王忻辰',
        url: 'http://music.ruoyi.vip/mishihuanjing',
        cover: './music/cover/wangxinchen.jpg',
        theme: '#46718b'
    }, {
        name: '执迷不悟',
        artist: '小乐哥',
        url: 'http://music.ruoyi.vip/zhimibuwu',
        cover: './music/cover/xiaolege.jpg',
        theme: '#46718b'
    }, {
        name: '浪子闲话',
        artist: '花僮',
        url: 'http://music.ruoyi.vip/langzixianhua',
        cover: './music/cover/huatong.jpg',
        theme: '#ebd0c2'
    }, {
        name: '你不配我的泪',
        artist: '付豪',
        url: 'http://music.ruoyi.vip/nbpwdl',
        cover: './music/cover/fuhao.jpg',
        theme: '#46718b'
    }, {
        name: '沉醉的青丝',
        artist: '夏艺韩',
        url: 'http://music.ruoyi.vip/chenzuideqingsi',
        cover: './music/cover/xiayihan.jpg',
        theme: '#46718b'
    }, {
        name: '大天蓬',
        artist: '清水er',
        url: 'http://music.ruoyi.vip/datianpeng',
        cover: './music/cover/qingshui.jpg',
        theme: '#ebd0c2'
    }, {
        name: '醉倾城',
        artist: '小阿枫',
        url: 'http://music.ruoyi.vip/zuiqingcheng',
        cover: './music/cover/xiaoafeng.jpg',
        theme: '#46718b'
    }, {
        name: '不过人间',
        artist: '海来阿木',
        url: 'http://music.ruoyi.vip/buguorenjian',
        cover: './music/cover/hailaiamu.jpg',
        theme: '#46718b'
    }, {
        name: '笑纳',
        artist: '花僮',
        url: 'http://music.ruoyi.vip/xiaona',
        cover: './music/cover/huatong.jpg',
        theme: '#ebd0c2'
    }, {
        name: '游京',
        artist: '海伦',
        url: 'http://music.ruoyi.vip/youjin',
        cover: './music/cover/hailun.jpg',
        theme: '#46718b'
    }, {
        name: '忘川彼岸',
        artist: '零一九零贰',
        url: 'http://music.ruoyi.vip/wangchuangbian',
        cover: './music/cover/01902.jpg',
        theme: '#46718b'
    }, {
        name: '游山恋',
        artist: '海伦',
        url: 'http://music.ruoyi.vip/youshanlian',
        cover: './music/cover/hailun.jpg',
        theme: '#46718b'
    }, {
        name: '光明',
        artist: '赵梓婷',
        url: 'http://music.ruoyi.vip/guangming',
        cover: './music/cover/zhaoziting.jpg',
        theme: '#ebd0c2'
    }, {
        name: '兄弟想你了',
        artist: '潇公子',
        url: 'http://music.ruoyi.vip/xiongdixiangnile',
        cover: './music/cover/xiaogongzi.jpg',
        theme: '#46718b'
    }, {
        name: '飞鸟和蝉',
        artist: '任然',
        url: 'http://music.ruoyi.vip/feiniaohechan',
        cover: './music/cover/renran.jpg',
        theme: '#ebd0c2'
    }, {
        name: '你快听滴答滴',
        artist: '龙儿',
        url: 'http://ruoyi.vip/music/mp3/龙儿 - 你快听滴答滴.mp3',
        cover: './music/cover/longer.jpg',
        theme: '#46718b'
    }, {
        name: '热火斯卡拉',
        artist: '承利',
        url: 'http://music.ruoyi.vip/rehuosikala',
        cover: './music/cover/chengli.jpg',
        theme: '#46718b'
    }, {
        name: '凤舞九天',
        artist: '承利',
        url: 'http://music.ruoyi.vip/fengwujiutian',
        cover: './music/cover/chengli.jpg',
        theme: '#46718b'
    }, {
        name: '春庭雪',
        artist: '等什么君',
        url: 'http://music.ruoyi.vip/chuntingxue',
        cover: './music/cover/dengshenmejun.jpg',
        theme: '#ebd0c2'
    }, {
        name: '夏天的风',
        artist: 'Uu',
        url: 'http://music.ruoyi.vip/xiatiandefeng',
        cover: './music/cover/uu.jpg',
        theme: '#ebd0c2'
    }, {
        name: '微微',
        artist: '傅如乔',
        url: 'http://music.ruoyi.vip/weiwei',
        cover: './music/cover/furuqiao.jpg',
        theme: '#ebd0c2'
    }, {
        name: '你若三冬',
        artist: '阿悠悠',
        url: 'http://music.ruoyi.vip/niruosandong',
        cover: './music/cover/ayouyou.jpg',
        theme: '#ebd0c2'
    }, {
        name: '一生与你擦肩而过',
        artist: '阿悠悠',
        url: 'http://music.ruoyi.vip/ysyncjeg',
        cover: './music/cover/ayouyou.jpg',
        theme: '#ebd0c2'
    }, {
        name: '再见只是陌生人',
        artist: '庄心妍',
        url: 'http://music.ruoyi.vip/zjzsmsr',
        cover: './music/cover/zhuangxinyan.jpg',
        theme: '#ebd0c2'
    }, {
        name: '无人之岛',
        artist: '任然',
        url: 'http://music.ruoyi.vip/wurenzhidao',
        cover: './music/cover/renran.jpg',
        theme: '#ebd0c2'
    }, {
        name: '辞九门回忆',
        artist: '等什么君',
        url: 'http://music.ruoyi.vip/cijiumenhuiyi',
        cover: './music/cover/dengshenmejun.jpg',
        theme: '#ebd0c2'
    }, {
        name: '惊雷',
        artist: '皮卡丘多多',
        url: 'http://music.ruoyi.vip/jinglei',
        cover: './music/cover/pikaqiuduoduo.jpg',
        theme: '#ebd0c2'
    }, {
        name: '旧梦一场',
        artist: '阿悠悠',
        url: 'http://music.ruoyi.vip/jiumengyichang',
        cover: './music/cover/ayouyou.jpg',
        theme: '#ebd0c2'
    }, {
        name: '想起了你',
        artist: '程响',
        url: 'http://music.ruoyi.vip/xiangqileni',
        cover: './music/cover/chengxiang.jpg',
        theme: '#ebd0c2'
    }, {
        name: '回到夏天',
        artist: '爱写歌的小田,傲七爷',
        url: 'http://music.ruoyi.vip/huidaoxiatian',
        cover: './music/cover/aoqiye.jpg',
        theme: '#ebd0c2'
    }, {
        name: '苏幕遮',
        artist: '张晓棠',
        url: 'http://music.ruoyi.vip/shuzhemu',
        cover: './music/cover/zhangxiaotang.jpg',
        theme: '#ebd0c2'
    }, {
        name: '万有引力',
        artist: 'Fyy',
        url: 'http://music.ruoyi.vip/wanyouyinli',
        cover: './music/cover/fyy.jpg',
        theme: '#ebd0c2'
    }, {
        name: '莫问归期',
        artist: '蒋雪儿',
        url: 'http://music.ruoyi.vip/mowenguiqi',
        cover: './music/cover/jiangxueer.jpg',
        theme: '#ebd0c2'
    }, {
        name: '点歌的人',
        artist: '海来阿木',
        url: 'http://music.ruoyi.vip/diangederen',
        cover: './music/cover/hailaiamu.jpg',
        theme: '#46718b'
    }, {
        name: '后来遇见他',
        artist: '胡66',
        url: 'http://music.ruoyi.vip/houlaiyujianta',
        cover: './music/cover/hu66.jpg',
        theme: '#ebd0c2'
    }, {
        name: '赤伶',
        artist: 'HITA',
        url: 'http://music.ruoyi.vip/chiling',
        cover: './music/cover/hita.jpg',
        theme: '#ebd0c2'
    }, {
        name: '嚣张',
        artist: '祁闻冥轩',
        url: 'http://music.ruoyi.vip/xiaozhang',
        cover: './music/cover/qiwenmingxuan.jpg',
        theme: '#46718b'
    }, {
        name: '少年',
        artist: '梦然',
        url: 'http://music.ruoyi.vip/shaonian',
        cover: './music/cover/mengran.jpg',
        theme: '#ebd0c2'
    }, {
        name: '一个人挺好',
        artist: '周森',
        url: 'http://music.ruoyi.vip/yigerentinghao',
        cover: './music/cover/zhoushen.jpg',
        theme: '#ebd0c2'
    }, {
        name: '你笑起来真好看',
        artist: '刘苏萱',
        url: 'http://music.ruoyi.vip/nxqlzhk',
        cover: './music/cover/liusuxuan.jpg',
        theme: '#ebd0c2'
    }, {
        name: '世界这么大还是遇见你',
        artist: '程响',
        url: 'http://music.ruoyi.vip/sjnmdhsyjn',
        cover: './music/cover/chengxiang.jpg',
        theme: '#ebd0c2'
    }, {
        name: '百花香',
        artist: '魏新雨',
        url: 'http://music.ruoyi.vip/baihuaxiang',
        cover: './music/cover/weixinyu.jpg',
        theme: '#ebd0c2'
    }, {
        name: '下山',
        artist: '要不要买菜',
        url: 'http://music.ruoyi.vip/xiashan',
        cover: './music/cover/ybymc.jpg',
        theme: '#46718b'
    }, {
        name: '桥边姑娘',
        artist: '张茜',
        url: 'http://ruoyi.vip/music/mp3/张茜 - 桥边姑娘.mp3',
        cover: './music/cover/zhangqian.jpg',
        theme: '#ebd0c2'
    }, {
        name: '你的答案',
        artist: '阿冗',
        url: 'http://music.ruoyi.vip/nidedaan',
        cover: './music/cover/arong.jpg',
        theme: '#46718b'
    }, {
        name: '生而为人',
        artist: '尚士达',
        url: 'http://music.ruoyi.vip/shengerweiren',
        cover: './music/cover/shangshida.jpg',
        theme: '#46718b'
    }, {
        name: '火红的萨日朗',
        artist: '要不要买菜',
        url: 'http://music.ruoyi.vip/huohongdesarilang',
        cover: './music/cover/ybymc.jpg',
        theme: '#46718b'
    }, {
        name: '画',
        artist: '韩甜甜',
        url: 'http://music.ruoyi.vip/hua',
        cover: './music/cover/hantiantian.jpg',
        theme: '#ebd0c2'
    }, {
        name: '飞云之下',
        artist: '韩甜甜',
        url: 'http://ruoyi.vip/music/mp3/韩甜甜 - 飞云之下.mp3',
        cover: './music/cover/hantiantian.jpg',
        theme: '#ebd0c2'
    }, {
        name: '世间美好与你环环相扣',
        artist: '柏松',
        url: 'http://music.ruoyi.vip/sjmhynhhxk',
        cover: './music/cover/baisong.jpg',
        theme: '#46718b'
    }, {
        name: '大田後生仔',
        artist: '丫蛋蛋',
        url: 'http://music.ruoyi.vip/datianhoushengzai',
        cover: './music/cover/yadandan.jpg',
        theme: '#ebd0c2'
    }, {
        name: '野狼disco',
        artist: '宝石Gem',
        url: 'http://music.ruoyi.vip/yelangdisco',
        cover: './music/cover/gem.jpg',
        theme: '#46718b'
    }, {
        name: '像我这样的人',
        artist: '毛不易',
        url: 'http://music.ruoyi.vip/xwzydr',
        cover: './music/cover/maobuyi.jpg',
        theme: '#46718b'
    }, {
        name: '孤芳自赏',
        artist: '杨小壮',
        url: 'http://music.ruoyi.vip/gufangzishang',
        cover: './music/cover/yangxiaozhuang.jpg',
        theme: '#46718b'
    }, {
        name: '别想她',
        artist: '小阿枫',
        url: 'http://ruoyi.vip/music/mp3/小阿枫 - 别想她.mp3',
        cover: './music/cover/xiaoafeng.jpg',
        theme: '#46718b'
    }, {
        name: '最远的你是我最近的爱',
        artist: '小阿枫',
        url: 'http://music.ruoyi.vip/zydnswzjda',
        cover: './music/cover/xiaoafeng.jpg',
        theme: '#46718b'
    }, {
        name: '想死却又不敢',
        artist: '井胧',
        url: 'http://music.ruoyi.vip/xiangsiqueyoubugan',
        cover: './music/cover/jinglong.jpg',
        theme: '#46718b'
    }, {
        name: '把孤独当做晚餐',
        artist: '南铃子',
        url: 'http://music.ruoyi.vip/bgddzwc',
        cover: './music/cover/nanlingzi.jpg',
        theme: '#ebd0c2'
    }, {
        name: 'Lil Mama',
        artist: 'Jain',
        url: 'http://music.ruoyi.vip/Lil-Mama',
        cover: './music/cover/Jain.jpg',
        theme: '#ebd0c2'
    }, {
        name: '红昭愿',
        artist: '音阙诗听',
        url: 'http://music.ruoyi.vip/hongzhaoyuan',
        cover: './music/cover/yinqueshiting.jpg',
        theme: '#ebd0c2'
    }, {
        name: '我曾',
        artist: '隔壁老樊',
        url: 'http://music.ruoyi.vip/woceng',
        cover: './music/cover/gebilaofan.jpg',
        theme: '#46718b'
    }, {
        name: '多想在平庸的生活拥抱你',
        artist: '隔壁老樊',
        url: 'http://music.ruoyi.vip/dxzpydshybn',
        cover: './music/cover/gebilaofan.jpg',
        theme: '#46718b'
    }, {
        name: '走马',
        artist: '摩登兄弟',
        url: 'http://music.ruoyi.vip/zouma',
        cover: './music/cover/modengxiongdi.jpg',
        theme: '#46718b'
    }, {
        name: '病变',
        artist: '江澈',
        url: 'http://music.ruoyi.vip/bingbian',
        cover: './music/cover/jiangche.jpg',
        theme: '#46718b'
    }, {
        name: '浪人琵琶',
        artist: '胡66',
        url: 'http://music.ruoyi.vip/langrenpipa',
        cover: './music/cover/hu66.jpg',
        theme: '#ebd0c2'
    }, {
        name: '芒种',
        artist: '赵方婧',
        url: 'http://music.ruoyi.vip/mangzhong',
        cover: './music/cover/zhaofangqian.jpg',
        theme: '#ebd0c2'
    }, {
        name: '逆流成河',
        artist: '金南玲',
        url: 'http://music.ruoyi.vip/niliuchenghe',
        cover: './music/cover/jinnanling.jpg',
        theme: '#ebd0c2'
    }, {
        name: '写给黄淮',
        artist: '张怡',
        url: 'http://music.ruoyi.vip/xiegeihuanghuai',
        cover: './music/cover/zhangyi.jpg',
        theme: '#ebd0c2'
    }, {
        name: '东西',
        artist: '林俊呈',
        url: 'http://music.ruoyi.vip/dongxi',
        cover: './music/cover/linjunchen.jpg',
        theme: '#46718b'
    }, {
        name: '选择失忆',
        artist: '季彦霖',
        url: 'http://music.ruoyi.vip/xuanzeshiyi',
        cover: './music/cover/bukaopu.jpg',
        theme: '#ebd0c2'
    }, {
        name: '38度6',
        artist: '黑龙',
        url: 'http://music.ruoyi.vip/38du6',
        cover: './music/cover/heilong.jpg',
        theme: '#ebd0c2'
    }, {
        name: '童话镇',
        artist: '陈一发',
        url: 'http://ruoyi.vip/music/mp3/陈一发 - 童话镇.mp3',
        cover: './music/cover/chenyifa.jpg',
        theme: '#ebd0c2'
    }, {
        name: '夜之光',
        artist: '花姐',
        url: 'http://music.ruoyi.vip/yezhiguang',
        cover: './music/cover/huajie.jpg',
        theme: '#ebd0c2'
    }, {
        name: '那个人',
        artist: '周延英',
        url: 'http://music.ruoyi.vip/nageren',
        cover: './music/cover/zhouyanying.jpg',
        theme: '#ebd0c2'
    }, {
        name: '9420',
        artist: '麦小兜',
        url: 'http://music.ruoyi.vip/9420',
        cover: './music/cover/maixiaodou.jpg',
        theme: '#ebd0c2'
    }, {
        name: '春风吹',
        artist: '阿冷',
        url: 'http://music.ruoyi.vip/chuifengchui',
        cover: './music/cover/aleng.jpg',
        theme: '#ebd0c2'
    }, {
        name: '来自天堂的魔鬼',
        artist: '邓紫棋',
        url: 'http://music.ruoyi.vip/lzttdmg',
        cover: './music/cover/dengziqi.jpg',
        theme: '#ebd0c2'
    }, {
        name: '倒数',
        artist: '邓紫棋',
        url: 'http://music.ruoyi.vip/daoshu',
        cover: './music/cover/dengziqi.jpg',
        theme: '#ebd0c2'
    }, {
        name: '光年之外',
        artist: '邓紫棋',
        url: 'http://music.ruoyi.vip/guangnianzhiwai',
        cover: './music/cover/dengziqi.jpg',
        theme: '#ebd0c2'
    }, {
        name: '不再犹豫',
        artist: 'Beyond',
        url: 'http://music.ruoyi.vip/buzaiyouyu',
        cover: './music/cover/Beyond.jpg',
        theme: '#ebd0c2'
    }, {
        name: '大地',
        artist: 'Beyond',
        url: 'http://music.ruoyi.vip/dadi',
        cover: './music/cover/Beyond.jpg',
        theme: '#ebd0c2'
    }, {
        name: '光辉岁月',
        artist: 'Beyond',
        url: 'http://music.ruoyi.vip/guanghuisuiyue',
        cover: './music/cover/Beyond.jpg',
        theme: '#ebd0c2'
    }, {
        name: '海阔天空',
        artist: 'Beyond',
        url: 'http://music.ruoyi.vip/haikuotiankong',
        cover: './music/cover/Beyond.jpg',
        theme: '#ebd0c2'
    }, {
        name: '灰色轨迹',
        artist: 'Beyond',
        url: 'http://music.ruoyi.vip/huiseguiji',
        cover: './music/cover/Beyond.jpg',
        theme: '#ebd0c2'
    }, {
        name: '冷雨夜',
        artist: 'Beyond',
        url: 'http://music.ruoyi.vip/lengyeyu',
        cover: './music/cover/Beyond.jpg',
        theme: '#ebd0c2'
    }, {
        name: '情人',
        artist: 'Beyond',
        url: 'http://music.ruoyi.vip/qingren',
        cover: './music/cover/Beyond.jpg',
        theme: '#ebd0c2'
    }, {
        name: '谁伴我闯荡',
        artist: 'Beyond',
        url: 'http://music.ruoyi.vip/shuibanwochuangdang',
        cover: './music/cover/Beyond.jpg',
        theme: '#ebd0c2'
    }, {
        name: '喜欢你',
        artist: 'Beyond',
        url: 'http://music.ruoyi.vip/xihuanni',
        cover: './music/cover/Beyond.jpg',
        theme: '#ebd0c2'
    }, {
        name: '真的爱你',
        artist: 'Beyond',
        url: 'http://music.ruoyi.vip/zhendeaini',
        cover: './music/cover/Beyond.jpg',
        theme: '#ebd0c2'
    }, {
        name: 'The Spectre',
        artist: 'Alan Walker',
        url: 'http://music.ruoyi.vip/the-spectre',
        cover: './music/cover/AlanWalker.jpg',
        theme: '#46718b'
    },  {
        name: 'All Falls Down',
        artist: 'Alan Walker',
        url: 'http://music.ruoyi.vip/all-falls-down',
        cover: './music/cover/AlanWalker.jpg',
        theme: '#46718b'
    },  {
        name: 'Alone',
        artist: 'Alan Walker',
        url: 'http://music.ruoyi.vip/alone',
        cover: './music/cover/AlanWalker.jpg',
        theme: '#46718b'
    }, {
        name: 'Faded',
        artist: 'Alan Walker',
        url: 'http://music.ruoyi.vip/faded',
        cover: './music/cover/AlanWalker.jpg',
        theme: '#46718b'
    }, {
        name: 'PDD 洪荒之力',
        artist: 'Hoaprox',
        url: 'http://music.ruoyi.vip/honghuanzhili',
        cover: './music/cover/Hoaprox.jpg',
        theme: '#46718b'
    }, {
        name: 'Kattrina',
        artist: 'Fly Project',
        url: 'http://music.ruoyi.vip/kattrina',
        cover: './music/cover/FlyProject.jpg',
        theme: '#46718b'
    }, {
        name: 'Zuehlsdorff',
        artist: 'Vicetone',
        url: 'http://music.ruoyi.vip/way-back',
        cover: './music/cover/Vicetone.jpg',
        theme: '#46718b'
    }, {
        name: 'Run Free',
        artist: 'Deep Chills',
        url: 'http://music.ruoyi.vip/run-free',
        cover: './music/cover/DeepChills.jpg',
        theme: '#46718b'
    }, {
        name: 'Something Just Like This',
        artist: 'The Chainsmokers',
        url: 'http://music.ruoyi.vip/something-just-like-this',
        cover: './music/cover/TheChainsmokers.jpg',
        theme: '#46718b'
    }, {
        name: 'Wild',
        artist: 'Monogem',
        url: 'http://music.ruoyi.vip/wild',
        cover: './music/cover/Monogem.jpg',
        theme: '#46718b'
    }, {
        name: 'Sunshine Girl',
        artist: 'Moumoon',
        url: 'http://music.ruoyi.vip/sunshine-girl',
        cover: './music/cover/Moumoon.jpg',
        theme: '#46718b'
    }, {
        name: 'Friendships (Original Mix)',
        artist: 'Pascal Letoublon',
        url: 'http://music.ruoyi.vip/friendships',
        cover: './music/cover/PascalLetoublon.jpg',
        theme: '#46718b'
    }, {
        name: 'Williams - Lullaby',
        artist: 'R3hab,Mike',
        url: 'http://music.ruoyi.vip/lullaby',
        cover: './music/cover/R3hab.jpg',
        theme: '#46718b'
    }, {
        name: 'Move Your Body (Alan Walker Remix)',
        artist: 'Sia,Alan Walker',
        url: 'http://music.ruoyi.vip/move-your-body',
        cover: './music/cover/AlanWalker.jpg',
        theme: '#46718b'
    }, {
        name: 'Unity',
        artist: 'The Fat Rat',
        url: 'http://music.ruoyi.vip/unity',
        cover: './music/cover/TheFatRat.jpg',
        theme: '#46718b'
    }, {
        name: 'Seve',
        artist: 'Tez Cadey',
        url: 'http://music.ruoyi.vip/seve',
        cover: './music/cover/TezCadey.jpg',
        theme: '#46718b'
    }, {
        name: '一曲相思',
        artist: '阿悠悠',
        url: 'http://music.ruoyi.vip/yiquxiangsi',
        cover: './music/cover/ayouyou.jpg',
        theme: '#ebd0c2'
    }, {
        name: '流浪',
        artist: '半阳',
        url: 'http://music.ruoyi.vip/liulang',
        cover: './music/cover/banyang.jpg',
        theme: '#46718b'
    }, {
        name: '画',
        artist: '赵雷',
        url: 'http://music.ruoyi.vip/zlhua',
        cover: './music/cover/zhaolei.jpg',
        theme: '#46718b'
    }, {
        name: '说书人',
        artist: '暗杠,寅子',
        url: 'http://music.ruoyi.vip/shuoshuren',
        cover: './music/cover/angang.jpg',
        theme: '#46718b'
    }, {
        name: '不染',
        artist: '简弘亦',
        url: 'http://music.ruoyi.vip/buran',
        cover: './music/cover/jianhongyi.jpg',
        theme: '#46718b'
    }, {
        name: '陷阱',
        artist: '王北车',
        url: 'http://music.ruoyi.vip/xianjing',
        cover: './music/cover/wangbeiche.jpg',
        theme: '#46718b'
    }, {
        name: '遥远的你',
        artist: '不靠谱组合',
        url: 'http://music.ruoyi.vip/yaoyuandeni',
        cover: './music/cover/bukaopu.jpg',
        theme: '#ebd0c2'
    }, {
        name: '月牙湾',
        artist: '刘至佳',
        url: 'http://music.ruoyi.vip/yueyawan',
        cover: './music/cover/liuzhijia.jpg',
        theme: '#ebd0c2'
    }, {
        name: '去年夏天',
        artist: '王大毛',
        url: 'http://music.ruoyi.vip/qunianxiatian',
        cover: './music/cover/wangdamao.jpg',
        theme: '#46718b'
    }, {
        name: '带你去旅行',
        artist: '校长',
        url: 'http://music.ruoyi.vip/dainiqulvxing',
        cover: './music/cover/xiaozhang.jpg',
        theme: '#46718b'
    }, {
        name: '心如止水',
        artist: 'Ice Paper',
        url: 'http://music.ruoyi.vip/xinruzhishui',
        cover: './music/cover/IcePape.jpg',
        theme: '#46718b'
    }, {
        name: '侧脸',
        artist: '于果',
        url: 'http://music.ruoyi.vip/celian',
        cover: './music/cover/yuguo.jpg',
        theme: '#ebd0c2'
    }, {
        name: '绿色',
        artist: '陈雪凝',
        url: 'http://music.ruoyi.vip/lvse',
        cover: './music/cover/chenxuening.jpg',
        theme: '#ebd0c2'
    }, {
        name: '出山',
        artist: '花粥',
        url: 'http://music.ruoyi.vip/chushan',
        cover: './music/cover/huazhou.jpg',
        theme: '#ebd0c2'
    }, {
        name: '遥不可及的你',
        artist: '花粥',
        url: 'http://music.ruoyi.vip/yaobukejideni',
        cover: './music/cover/huazhou.jpg',
        theme: '#ebd0c2'
    }, {
        name: '相思如意',
        artist: '兔子牙',
        url: 'http://music.ruoyi.vip/xiangsiruyi',
        cover: './music/cover/tuziya.jpg',
        theme: '#505d6b'
    }, {
        name: '江南夜色',
        artist: '程响',
        url: 'http://music.ruoyi.vip/jiangnanyese',
        cover: './music/cover/chengxiang.jpg',
        theme: '#46718b'
    }, {
        name: '过客',
        artist: '周思涵',
        url: 'http://music.ruoyi.vip/guoke',
        cover: './music/cover/zhousihan.jpg',
        theme: '#505d6b'
    }, {
        name: '年少有为',
        artist: '李荣浩',
        url: 'http://music.ruoyi.vip/nianshaoyouwei',
        cover: './music/cover/lironghao.jpg',
        theme: '#46718b'
    }, {
        name: '曾经的你',
        artist: '许巍',
        url: 'http://music.ruoyi.vip/cengjingdeni',
        cover: './music/cover/xuwei.jpg',
        theme: '#46718b'
    }, {
        name: '出现又离开',
        artist: '梁博',
        url: 'http://music.ruoyi.vip/chuxianyoulikai',
        cover: './music/cover/liangbo.jpg',
        theme: '#46718b'
    }, {
        name: 'A Little Story',
        artist: 'Valentin',
        url: 'http://music.ruoyi.vip/a-little-story',
        cover: './music/cover/Valentin.jpg',
        theme: '#46718b'
    }]
});